### ISSUE TITLE
List of # of Request under 1 hour

### ISSUE THREAD

**Issue by mcgarveyd** [ZackvM/ssv4#107]
same as other issues except I need the full list with the INV/PR/REQ IDs for request under 1 hour

**Comment by ZackvM** [comment]
SELECT iv.investid, invest_division, invest_fname, invest_lname, invest_homeinstitute
,invest_institutiontype, pr.projid, rq.requestid, req_postexcisiontime, req_surgeryunit, 'Active Investigator 1HR 2015' as title
FROM vandyinvest.activeinvesttissreq rq
left outer join vandyinvest.activeinvestproj pr on rq.projid = pr.projid
left outer join vandyinvest.activeInvest iv on pr.investid = iv.investid 
where 
(req_surgeryunit = 'Hrs' and trim(req_postexcisiontime) = '1')
or
(req_surgeryunit = 'Hrs' and trim(req_postexcisiontime) = '1.0')
or 
(req_surgeryUnit = 'Min' and trim(req_postexcisiontime) = '60')
order by iv.investid,pr.projid, rq.requestid
