### ISSUE TITLE
 BUG #5 Setup User modification bug

### ISSUE THREAD

**Issue by mcgarveyd** [ZackvM/ssv4#12]
The system stalls if I try to modify an established user AFTER I have already done some other action on this screen. This does not occur if modifying the user is the first action that I attempt on this screen. I can only get out of the stall by hitting refresh and then going back to the user.

**Comment by ZackvM** [comment]
A data field was missing in the update grid of the user display ... added userid to the query - Fixed Problem ... Will update repository on next commit ... 

SELECT userid, substr(concat('00000',userid), -4) as usrid, concat(ifnull(displayName,''), ' [',ifnull(userLogin,''),']') dspName, accessLevel, allowind FROM four.sys_userbase where accessLevel is not null  order by displayName asc
